// USER
export const GET_USER_PROFILE = 'GET_USER';
export const SET_ACCOUNT_TYPE = 'SET_ACCOUNT_TYPE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_CLIENT_PROFILE = 'GET_CLIENT_PROFILE';
export const FETCH_GROOMER_PROFILE = 'FETCH_GROOMER_PROFILE';

// SEARCH
export const SEARCH_ALL_GROOMERS = 'SEARCH_ALL_GROOMERS';
export const SEARCH_GROOMERS_BY = 'SEARCH_GROOMERS_BY';
export const CLEAR_GROOMER = 'CLEAR_GROOMER';

// USER AND SEARCH
export const GET_GROOMER_PROFILE = 'GET_GROOMER_PROFILE';

// DASHBOARD
export const SET_DASHBOARD_VIEW = 'SET_DASHBOARD_VIEW';
export const SET_PET_TO_UPDATE = 'SET_PET_TO_UPDATE';
