// USER
export const GET_USER_PROFILE = 'GET_USER';
export const SET_ACCOUNT_TYPE = 'SET_ACCOUNT_TYPE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

// SEARCH
export const SEARCH_ALL_GROOMERS = 'SEARCH_ALL_GROOMERS';
export const SEARCH_GROOMERS_BY = 'SEARCH_GROOMERS_BY';
export const CLEAR_GROOMER = 'CLEAR_GROOMER';

// USER AND SEARCH
export const GET_GROOMER_PROFILE = 'GET_GROOMER_PROFILE';
