// CLIENT
export const GET_CLIENT = 'GET_CLIENT';
export const SEARCH_GROOMERS = 'SEARCH_GROOMERS';

// SEARCH
export const SEARCH_ALL_GROOMERS = 'SEARCH_ALL_GROOMERS';
export const SEARCH_GROOMERS_BY = 'SEARCH_GROOMERS_BY';
export const GET_GROOMER_PROFILE = 'GET_GROOMER_PROFILE';
export const CLEAR_GROOMER = 'CLEAR_GROOMER';
